### PR TITLE
Fixing compilation on windows

### PR DESCRIPTION
**Pull request by mantelt**
compilation works on my Windows 7 installation, using Qt 5.7.1 and MSVC 2015

### CODE REVIEW

**Comment by philipoe** [comment]
Ouh great, thanks! Some questions for understanding:

 - Just changing src/ui/LED.hIs is not sufficient, right? 
 - Are the changes to the QGCExternalLibs.pri something that should be pushed to standard QGC repo?

**Comment by mantelt** [comment]
just changing LED.h is sufficient to compile the energy widget on windows.

the changes on QGCExternalLibs.pri is something that I'm currently testing on the upstream QGC. It did not link properly using the unchanged file (as it took the 32bit version of the library).

If the upstream QGC does not compile out of the box without my changes, I will make a PR for my changes there.

**Comment by mantelt** [comment]
OK, so I made a PR on the upstream qgroundcontrol just solving the issue with the SDL library (change to QGCExternalLibs.pri).
Should we wait for it to go through there and then redo this PR here, cherry-picking the commit from upstream and fixing the LED issue in another commit?

**Comment by philipoe** [comment]
I'd agree that given that it is apparently only me who is working with this on Windows at the moment, and in addition you now created this nice fix-branch, we should wait for the PR@Upstream to go through and then just fix the LED.h. Let's keep this PR open in any case for discussions.

**Comment by mantelt** [comment]
OK, so the changes to the QGCExternalLibs.pri is through on upstream (mavlink/qgroundcontrol#5373).

Created new branch with new PR (#42)

**Pull request closed without merging**
